ver;
ver=1.0.1
||
1.0.0;
desc=Base version;
link=https://forums.skunity.com/resources/blockedit.890/history
||
1.0.1;
desc=Updated error message;
link=https://forums.skunity.com/resources/blockedit.890/history;
/=Removed unnecesary code on fill;
/=Removed unnecesary code on replace;
/=Error message
||
1.0.2;
desc=Update detector;
link=https://forums.skunity.com/resources/blockedit.890/history;
+=Update detection;
+=Notify when updated
